# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# ref : https://qiita.com/koreyou/items/00f5820591ec9196ef07
import os
import sys
import sphinx.ext.apidoc

root_dir = os.path.abspath('../..')

try:
    import ttt
    import ttt.__version__
    import ttt.__metadata__
except ImportError:
    sys.path.insert(0, root_dir)
    import ttt
    import ttt.__version__
    import ttt.__metadata__

sys.path.insert(0, os.path.abspath('../{}'.format(ttt.__name__)))

# -- Project information -----------------------------------------------------

# project = 'sample'
# copyright = '2021, yu_satou'
# author = 'yu_satou'

# The full version, including alpha/beta/rc tags
# release = '0.0.0'

project = ttt.__name__
version = ttt.__version__.__version__
release = ttt.__version__.__version__  # I don't know where be used...
copyright = ttt.__metadata__.copyright
author = ttt.__metadata__.author

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc', 'sphinx.ext.napoleon'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
# language = 'jp'  # Isn't it "ja"? Occurs warning of not found.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = 'sphinx_rtd_theme'  # Needs >pip install sphinx_rtd_theme.

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Section for searching japanese wards.
# ref : https://r-square.net/sphinx/03_sphinx_mecab.html
# This code needs systemside package.
# Please install...
# > sudo apt install mecab mecab-ipadic
html_search_language = "ja"
html_search_options = {
    'type': 'sphinx.search.ja.MecabSplitter',
    'dic_enc': 'utf-8',
    'dict': "/var/lib/mecab/dic/ipadic",
}

# -- For enbeding sphinx-apidoc to sphinx-build ------------------------------

# ref : https://qiita.com/koreyou/items/00f5820591ec9196ef07
def run_apidoc(_):
    sphinx.ext.apidoc.main(
        ['-f',
         '-H', project,
         '-A', author,
         '-V', version,
         '-T',
         '-M',
         '-o', ttt.__metadata__.sphinx_apidoc_module_dir,
         ttt.__metadata__.sphinx_apidoc_source_dir]
    )

def setup(app):
    app.connect('builder-inited', run_apidoc)
